version: '3'

services:
  doctor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctor
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
    ports:
      - "8080:8080"
    depends_on: 
      - postgres
    networks:
      - net_3

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_DB: doctor
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - net_3

volumes:
  postgres-volume:
    driver: local

networks:
  net_3:
    driver: bridge
